source: app
destination: web

url: http://blog.title
permalink: pretty

encoding: utf-8

title: Yet another title.
description: Currently nothing but whitespace.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

external_one_title: Articles
external_one_url: journal.of.ekins.space
external_two_title: GitHub
external_two_url: github.com/ekinhbayar
external_three_title: Twitter
external_three_url: twitter.com/_ek1n
